-- drop table if exists
CREATE TABLE TASK_CATEGORIES
(
    CATEGORY_ID INT PRIMARY KEY NOT NULL,
    CATEGORY_NAME VARCHAR(100),
    CATEGORY_DESCRIPTION VARCHAR(500)
);

-- drop table if exists
CREATE TABLE TASKS
(
    TASK_ID INT  NOT NULL,
    TASK_NAME VARCHAR(100),
    TASK_DESCRIPTION VARCHAR(500),
    DEADLINE TIMESTAMP,
    CATEGORY_ID INT,
    PRIMARY KEY  (TASK_ID),
    foreign key (CATEGORY_ID) references TASK_CATEGORIES(CATEGORY_ID)
);
